version: "3"

services:
  app:
    build: .
    container_name: iluma-store-com-app
    restart: always
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=iluma-store.com, www.iluma-store.com
      - LETSENCRYPT_HOST=iluma-store.com, www.iluma-store.com
      - LETSENCRYPT_EMAIL=parsh@gmail.com
      - REDIRECT_www.iluma-store.com=iluma-store.com
    networks:
      - web
    volumes:
      # Все сайты используют одну и ту же папку с картинками
      - /var/www/iluma-store.ru/images:/app/public/images:ro
      # - /var/www/iluma-store.com/.next:/app/.next

networks:
  web:
    external: true
